version: '3.1'

services:
  mysql:
    image: mysql:5.7.22
    ports:
      - "8888:3306"
    hostname: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USERNAME=root
        - MYSQL_DATABASE=Users
  
  web:
    build: pictolearn-web
    image: web-img
    hostname: web
    tty: true
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - DB_PORT=tcp://mysql:3306  
  
  router:
    build: pictolearn-dispatcher
    image: disp-img
    ports:
      - "1111:8080"
    hostname: router
    tty: true
    environment:
      - CATALINE_BASE=/opt/tomcat
      - CATALINE_HOME=/opt/tomcat
    depends_on:
      - web
