version: '3.1' #version of Docker-compose

networks:
  rede:
  
services: #specifies 2 microservices "web" and "mysql"

  bancodb:
    image: mysql:5.7.22 # Expose a mysql image
    restart: always
    ports:
      - "8888:3306" # Expose port 8888
    hostname: mysqlw # mysql hostname
    environment: # root username and password
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=Users
    networks:
      - rede
    
  web: # Web microservice
    build: pictolearn-docker  # Dockerfile folder
    image: pictolearn-docker
    ports:
      - "5555:8080" # expose port 5555 for the rest client to connect to
    hostname: web
    tty: true
    volumes:
      - C:\users\servidor\desktop\logs:/usr/local/pictolearn/logs
    depends_on:
      - bancodb
    networks:
      - rede
    environment:
      - DB_PORT=tcp://mysql:3306
